// Routes:
const bidRouter = require('./routes/bid.routes');
app.use('/bids', bidRouter);
const categoryRouter = require('./routes/category.routes');
app.use('/categories', categoryRouter);
const emailRouter = require('./routes/email.routes');
app.use('/emails', emailRouter);
const employmentOfferRouter = require('./routes/employmentOffer.routes');
app.use('/employmentOffers', employmentOfferRouter);
const jobIdCategoryIdRouter = require('./routes/jobIdCategoryId.routes');
app.use('/jobIdCategoryIds', jobIdCategoryIdRouter);
const jobRouter = require('./routes/job.routes');
app.use('/jobs', jobRouter);
const skillLevelNamesRouter = require('./routes/skillLevelName.routes');
app.use('/skillLevelNames', skillLevelNamesRouter);
const teamInvitationRouter = require('./routes/teamInvitation.routes');
app.use('/teamInvitations', teamInvitationRouter);
const teamRoleRouter = require('./routes/teamRole.routes');
app.use('/teamRoles', teamRoleRouter);
const teamRouter = require('./routes/team.routes');
app.use('/users', teamRouter);
const userIdTeamIdRouter = require('./routes/userIdTeamId.routes');
app.use('/userIdTeamIds', userIdTeamIdRouter);
const userSkillRouter = require('./routes/userSkill.routes');
app.use('/userSkills', userSkillRouter);
const userRouter = require('./routes/user.routes');
app.use('/users', userRouter);
